### PR TITLE
Documentation: Change README

### PR DESCRIPTION
**Pull request by djdv**
There were some typos and I reworded one of sentences. I'm not sure if the bold to display the difference of file and data store is too much though, maybe italics would be better or no emphasis at all. What do you think of the emphasis and rewording?

### CODE REVIEW

**Comment by kevina** [comment]
I don't like the emphasis at all.

**Comment by kevina** [comment]
Other than that it looks good.  In order for me to accept the commit you need to add

```
License: MIT
Signed-off-by: NAME <EMAIL>
```

to the end of the commit (after replacing NAME and EMAIL with your name and email).  See https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages.

**Comment by djdv** [comment]
Should be all good now. Signed off and _de-emphasized_.

**Comment by kevina** [comment]
Thank you.  I cherry-picked the commit.

**Pull request closed without merging**
